### ISSUE TITLE
Flapping tests

### ISSUE THREAD

**Issue by AlexDaniel** [shinobi/Data-StaticTable#4]
On rakudo 2018.06 tests seem to be flapping. Sometimes `t/StaticTable-query.t` fails with:
```
not ok 27 - Can be serialized using .perl method
```

To see the issue you can run it in a loop, something like:
```bash
while PERL6LIB=lib/ prove --exec=perl6 t/StaticTable-query.t; do :; done
```

After `StaticTable-query.t` is fixed please also check `StaticTable-perf.t`, I *think* it is flapping too.

**Comment by shinobi** [comment]
I fixed it by removing the use of .race on a comparison over array elements. StaticTable.pm6 line 368.

**Comment by AlexDaniel** [comment]
Thank you!
